// Generated by scripts/generate-fgfdmexec-bindings.mjs.
// Do not edit manually.

#include <cstdint>
#include <memory>
#include <string>
#include <type_traits>
#include <vector>

#include <emscripten/bind.h>
#include <emscripten/val.h>

#include "FGFDMExec.h"

namespace {

using JSBSim::FGFDMExec;
using ::SGPath;

template <typename T>
std::enable_if_t<std::is_arithmetic_v<T>, T> toJsValue(T value) {
  return value;
}

template <typename T>
std::enable_if_t<std::is_enum_v<T>, int> toJsValue(T value) {
  return static_cast<int>(value);
}

inline std::string toJsValue(const std::string& value) {
  return value;
}

inline std::string toJsValue(std::string&& value) {
  return std::move(value);
}

inline std::string toJsValue(const SGPath& path) {
  return path.utf8Str();
}

inline emscripten::val toJsValue(const std::vector<std::string>& values) {
  emscripten::val out = emscripten::val::array();
  for (std::size_t i = 0; i < values.size(); ++i) {
    out.set(i, values[i]);
  }
  return out;
}

inline emscripten::val toJsValue(std::vector<std::string>& values) {
  return toJsValue(static_cast<const std::vector<std::string>&>(values));
}

template <typename T>
uintptr_t toJsValue(T* value) {
  return reinterpret_cast<uintptr_t>(value);
}

template <typename T>
uintptr_t toJsValue(const std::shared_ptr<T>& value) {
  return reinterpret_cast<uintptr_t>(value.get());
}

template <typename T>
uintptr_t toJsValue(const std::unique_ptr<T>& value) {
  return reinterpret_cast<uintptr_t>(value.get());
}

template <typename T>
uintptr_t toJsValue(T& value) {
  return reinterpret_cast<uintptr_t>(&value);
}

static void wrap_FGFDMExec_Unbind_0(FGFDMExec& self) {
  self.Unbind();
}

static auto wrap_FGFDMExec_Run_1(FGFDMExec& self) {
  return toJsValue(self.Run());
}

static auto wrap_FGFDMExec_RunIC_2(FGFDMExec& self) {
  return toJsValue(self.RunIC());
}

static auto wrap_FGFDMExec_LoadPlanet_3(FGFDMExec& self, const std::string& PlanetPath, bool useAircraftPath) {
  return toJsValue(self.LoadPlanet(SGPath(PlanetPath), useAircraftPath));
}

static auto wrap_FGFDMExec_LoadModel_4(FGFDMExec& self, const std::string& AircraftPath, const std::string& EnginePath, const std::string& SystemsPath, const std::string& model, bool addModelToPath) {
  return toJsValue(self.LoadModel(SGPath(AircraftPath), SGPath(EnginePath), SGPath(SystemsPath), model, addModelToPath));
}

static auto wrap_FGFDMExec_LoadModel_5(FGFDMExec& self, const std::string& model, bool addModelToPath) {
  return toJsValue(self.LoadModel(model, addModelToPath));
}

static auto wrap_FGFDMExec_LoadScript_6(FGFDMExec& self, const std::string& Script, double deltaT, const std::string& initfile) {
  return toJsValue(self.LoadScript(SGPath(Script), deltaT, SGPath(initfile)));
}

static auto wrap_FGFDMExec_SetEnginePath_7(FGFDMExec& self, const std::string& path) {
  return toJsValue(self.SetEnginePath(SGPath(path)));
}

static auto wrap_FGFDMExec_SetAircraftPath_8(FGFDMExec& self, const std::string& path) {
  return toJsValue(self.SetAircraftPath(SGPath(path)));
}

static auto wrap_FGFDMExec_SetSystemsPath_9(FGFDMExec& self, const std::string& path) {
  return toJsValue(self.SetSystemsPath(SGPath(path)));
}

static auto wrap_FGFDMExec_SetOutputPath_10(FGFDMExec& self, const std::string& path) {
  return toJsValue(self.SetOutputPath(SGPath(path)));
}

static auto wrap_FGFDMExec_GetAtmosphere_11(FGFDMExec& self) {
  return toJsValue(self.GetAtmosphere());
}

static auto wrap_FGFDMExec_GetAccelerations_12(FGFDMExec& self) {
  return toJsValue(self.GetAccelerations());
}

static auto wrap_FGFDMExec_GetWinds_13(FGFDMExec& self) {
  return toJsValue(self.GetWinds());
}

static auto wrap_FGFDMExec_GetFCS_14(FGFDMExec& self) {
  return toJsValue(self.GetFCS());
}

static auto wrap_FGFDMExec_GetPropulsion_15(FGFDMExec& self) {
  return toJsValue(self.GetPropulsion());
}

static auto wrap_FGFDMExec_GetMassBalance_16(FGFDMExec& self) {
  return toJsValue(self.GetMassBalance());
}

static auto wrap_FGFDMExec_GetAerodynamics_17(FGFDMExec& self) {
  return toJsValue(self.GetAerodynamics());
}

static auto wrap_FGFDMExec_GetInertial_18(FGFDMExec& self) {
  return toJsValue(self.GetInertial());
}

static auto wrap_FGFDMExec_GetGroundReactions_19(FGFDMExec& self) {
  return toJsValue(self.GetGroundReactions());
}

static auto wrap_FGFDMExec_GetExternalReactions_20(FGFDMExec& self) {
  return toJsValue(self.GetExternalReactions());
}

static auto wrap_FGFDMExec_GetBuoyantForces_21(FGFDMExec& self) {
  return toJsValue(self.GetBuoyantForces());
}

static auto wrap_FGFDMExec_GetAircraft_22(FGFDMExec& self) {
  return toJsValue(self.GetAircraft());
}

static auto wrap_FGFDMExec_GetPropagate_23(FGFDMExec& self) {
  return toJsValue(self.GetPropagate());
}

static auto wrap_FGFDMExec_GetAuxiliary_24(FGFDMExec& self) {
  return toJsValue(self.GetAuxiliary());
}

static auto wrap_FGFDMExec_GetInput_25(FGFDMExec& self) {
  return toJsValue(self.GetInput());
}

static auto wrap_FGFDMExec_GetOutput_26(FGFDMExec& self) {
  return toJsValue(self.GetOutput());
}

static auto wrap_FGFDMExec_GetScript_27(FGFDMExec& self) {
  return toJsValue(self.GetScript());
}

static auto wrap_FGFDMExec_GetIC_28(FGFDMExec& self) {
  return toJsValue(self.GetIC());
}

static auto wrap_FGFDMExec_GetTrim_29(FGFDMExec& self) {
  return toJsValue(self.GetTrim());
}

static auto wrap_FGFDMExec_GetEnginePath_30(FGFDMExec& self) {
  return toJsValue(self.GetEnginePath());
}

static auto wrap_FGFDMExec_GetAircraftPath_31(FGFDMExec& self) {
  return toJsValue(self.GetAircraftPath());
}

static auto wrap_FGFDMExec_GetSystemsPath_32(FGFDMExec& self) {
  return toJsValue(self.GetSystemsPath());
}

static auto wrap_FGFDMExec_GetFullAircraftPath_33(FGFDMExec& self) {
  return toJsValue(self.GetFullAircraftPath());
}

static auto wrap_FGFDMExec_GetOutputPath_34(FGFDMExec& self) {
  return toJsValue(self.GetOutputPath());
}

static auto wrap_FGFDMExec_GetPropertyValue_35(FGFDMExec& self, const std::string& property) {
  return toJsValue(self.GetPropertyValue(property));
}

static void wrap_FGFDMExec_SetPropertyValue_36(FGFDMExec& self, const std::string& property, double value) {
  self.SetPropertyValue(property, value);
}

static auto wrap_FGFDMExec_GetModelName_37(FGFDMExec& self) {
  return toJsValue(self.GetModelName());
}

static auto wrap_FGFDMExec_GetPropertyManager_38(FGFDMExec& self) {
  return toJsValue(self.GetPropertyManager());
}

static auto wrap_FGFDMExec_EnumerateFDMs_39(FGFDMExec& self) {
  return toJsValue(self.EnumerateFDMs());
}

static auto wrap_FGFDMExec_GetFDMCount_40(FGFDMExec& self) {
  return toJsValue(self.GetFDMCount());
}

static auto wrap_FGFDMExec_GetChildFDM_41(FGFDMExec& self, int i) {
  return toJsValue(self.GetChildFDM(i));
}

static void wrap_FGFDMExec_SetChild_42(FGFDMExec& self, bool ch) {
  self.SetChild(ch);
}

static auto wrap_FGFDMExec_SetOutputDirectives_43(FGFDMExec& self, const std::string& fname) {
  return toJsValue(self.SetOutputDirectives(SGPath(fname)));
}

static void wrap_FGFDMExec_ForceOutput_44(FGFDMExec& self, int idx) {
  self.ForceOutput(idx);
}

static void wrap_FGFDMExec_SetLoggingRate_45(FGFDMExec& self, double rate) {
  self.SetLoggingRate(rate);
}

static auto wrap_FGFDMExec_SetOutputFileName_46(FGFDMExec& self, int n, const std::string& fname) {
  return toJsValue(self.SetOutputFileName(n, fname));
}

static auto wrap_FGFDMExec_GetOutputFileName_47(FGFDMExec& self, int n) {
  return toJsValue(self.GetOutputFileName(n));
}

static void wrap_FGFDMExec_DoTrim_48(FGFDMExec& self, int mode) {
  self.DoTrim(mode);
}

static void wrap_FGFDMExec_DoLinearization_49(FGFDMExec& self, int arg0) {
  self.DoLinearization(arg0);
}

static void wrap_FGFDMExec_DisableOutput_50(FGFDMExec& self) {
  self.DisableOutput();
}

static void wrap_FGFDMExec_EnableOutput_51(FGFDMExec& self) {
  self.EnableOutput();
}

static void wrap_FGFDMExec_Hold_52(FGFDMExec& self) {
  self.Hold();
}

static void wrap_FGFDMExec_EnableIncrementThenHold_53(FGFDMExec& self, int Timesteps) {
  self.EnableIncrementThenHold(Timesteps);
}

static void wrap_FGFDMExec_CheckIncrementalHold_54(FGFDMExec& self) {
  self.CheckIncrementalHold();
}

static void wrap_FGFDMExec_Resume_55(FGFDMExec& self) {
  self.Resume();
}

static auto wrap_FGFDMExec_Holding_56(FGFDMExec& self) {
  return toJsValue(self.Holding());
}

static void wrap_FGFDMExec_ResetToInitialConditions_57(FGFDMExec& self, int mode) {
  self.ResetToInitialConditions(mode);
}

static void wrap_FGFDMExec_SetDebugLevel_58(FGFDMExec& self, int level) {
  self.SetDebugLevel(level);
}

static void wrap_FGFDMExec_BuildPropertyCatalog_59(FGFDMExec& self, uintptr_t pcs) {
  self.BuildPropertyCatalog(reinterpret_cast<FGFDMExec::PropertyCatalogStructure*>(pcs));
}

static auto wrap_FGFDMExec_QueryPropertyCatalog_60(FGFDMExec& self, const std::string& check, const std::string& end_of_line) {
  return toJsValue(self.QueryPropertyCatalog(check, end_of_line));
}

static void wrap_FGFDMExec_PrintPropertyCatalog_61(FGFDMExec& self) {
  self.PrintPropertyCatalog();
}

static void wrap_FGFDMExec_PrintSimulationConfiguration_62(FGFDMExec& self) {
  self.PrintSimulationConfiguration();
}

static auto wrap_FGFDMExec_GetPropertyCatalog_63(FGFDMExec& self) {
  return toJsValue(self.GetPropertyCatalog());
}

static void wrap_FGFDMExec_SetTrimStatus_64(FGFDMExec& self, bool status) {
  self.SetTrimStatus(status);
}

static auto wrap_FGFDMExec_GetTrimStatus_65(FGFDMExec& self) {
  return toJsValue(self.GetTrimStatus());
}

static void wrap_FGFDMExec_SetTrimMode_66(FGFDMExec& self, int mode) {
  self.SetTrimMode(mode);
}

static auto wrap_FGFDMExec_GetTrimMode_67(FGFDMExec& self) {
  return toJsValue(self.GetTrimMode());
}

static auto wrap_FGFDMExec_GetPropulsionTankReport_68(FGFDMExec& self) {
  return toJsValue(self.GetPropulsionTankReport());
}

static auto wrap_FGFDMExec_GetSimTime_69(FGFDMExec& self) {
  return toJsValue(self.GetSimTime());
}

static auto wrap_FGFDMExec_GetDeltaT_70(FGFDMExec& self) {
  return toJsValue(self.GetDeltaT());
}

static void wrap_FGFDMExec_SuspendIntegration_71(FGFDMExec& self) {
  self.SuspendIntegration();
}

static void wrap_FGFDMExec_ResumeIntegration_72(FGFDMExec& self) {
  self.ResumeIntegration();
}

static auto wrap_FGFDMExec_IntegrationSuspended_73(FGFDMExec& self) {
  return toJsValue(self.IntegrationSuspended());
}

static auto wrap_FGFDMExec_Setsim_time_74(FGFDMExec& self, double cur_time) {
  return toJsValue(self.Setsim_time(cur_time));
}

static void wrap_FGFDMExec_Setdt_75(FGFDMExec& self, double delta_t) {
  self.Setdt(delta_t);
}

static void wrap_FGFDMExec_SetRootDir_76(FGFDMExec& self, const std::string& rootDir) {
  self.SetRootDir(SGPath(rootDir));
}

static auto wrap_FGFDMExec_GetRootDir_77(FGFDMExec& self) {
  return toJsValue(self.GetRootDir());
}

static auto wrap_FGFDMExec_IncrTime_78(FGFDMExec& self) {
  return toJsValue(self.IncrTime());
}

static auto wrap_FGFDMExec_GetFrame_79(FGFDMExec& self) {
  return toJsValue(self.GetFrame());
}

static auto wrap_FGFDMExec_GetDebugLevel_80(FGFDMExec& self) {
  return toJsValue(self.GetDebugLevel());
}

static void wrap_FGFDMExec_Initialize_81(FGFDMExec& self, uintptr_t FGIC) {
  self.Initialize(reinterpret_cast<const JSBSim::FGInitialCondition*>(FGIC));
}

static void wrap_FGFDMExec_SetHoldDown_82(FGFDMExec& self, bool hd) {
  self.SetHoldDown(hd);
}

static auto wrap_FGFDMExec_GetHoldDown_83(FGFDMExec& self) {
  return toJsValue(self.GetHoldDown());
}

static auto wrap_FGFDMExec_GetTemplateFunc_84(FGFDMExec& self, const std::string& name) {
  return toJsValue(self.GetTemplateFunc(name));
}

static void wrap_FGFDMExec_AddTemplateFunc_85(FGFDMExec& self, const std::string& name, uintptr_t el) {
  self.AddTemplateFunc(name, reinterpret_cast<JSBSim::Element*>(el));
}

static auto wrap_FGFDMExec_GetRandomGenerator_86(FGFDMExec& self) {
  return toJsValue(self.GetRandomGenerator());
}

static auto wrap_FGFDMExec_SRand_87(FGFDMExec& self) {
  return toJsValue(self.SRand());
}

}  // namespace

EMSCRIPTEN_BINDINGS(jsbsim_fgfmdexec_bindings) {
  emscripten::class_<FGFDMExec>("FGFDMExec")
    .constructor<>()
    .function("Unbind", &wrap_FGFDMExec_Unbind_0)
    .function("Run", &wrap_FGFDMExec_Run_1)
    .function("RunIC", &wrap_FGFDMExec_RunIC_2)
    .function("LoadPlanet", &wrap_FGFDMExec_LoadPlanet_3)
    .function("LoadModel", &wrap_FGFDMExec_LoadModel_4)
    .function("LoadModel", &wrap_FGFDMExec_LoadModel_5)
    .function("LoadScript", &wrap_FGFDMExec_LoadScript_6)
    .function("SetEnginePath", &wrap_FGFDMExec_SetEnginePath_7)
    .function("SetAircraftPath", &wrap_FGFDMExec_SetAircraftPath_8)
    .function("SetSystemsPath", &wrap_FGFDMExec_SetSystemsPath_9)
    .function("SetOutputPath", &wrap_FGFDMExec_SetOutputPath_10)
    .function("GetAtmosphere", &wrap_FGFDMExec_GetAtmosphere_11)
    .function("GetAccelerations", &wrap_FGFDMExec_GetAccelerations_12)
    .function("GetWinds", &wrap_FGFDMExec_GetWinds_13)
    .function("GetFCS", &wrap_FGFDMExec_GetFCS_14)
    .function("GetPropulsion", &wrap_FGFDMExec_GetPropulsion_15)
    .function("GetMassBalance", &wrap_FGFDMExec_GetMassBalance_16)
    .function("GetAerodynamics", &wrap_FGFDMExec_GetAerodynamics_17)
    .function("GetInertial", &wrap_FGFDMExec_GetInertial_18)
    .function("GetGroundReactions", &wrap_FGFDMExec_GetGroundReactions_19)
    .function("GetExternalReactions", &wrap_FGFDMExec_GetExternalReactions_20)
    .function("GetBuoyantForces", &wrap_FGFDMExec_GetBuoyantForces_21)
    .function("GetAircraft", &wrap_FGFDMExec_GetAircraft_22)
    .function("GetPropagate", &wrap_FGFDMExec_GetPropagate_23)
    .function("GetAuxiliary", &wrap_FGFDMExec_GetAuxiliary_24)
    .function("GetInput", &wrap_FGFDMExec_GetInput_25)
    .function("GetOutput", &wrap_FGFDMExec_GetOutput_26)
    .function("GetScript", &wrap_FGFDMExec_GetScript_27)
    .function("GetIC", &wrap_FGFDMExec_GetIC_28)
    .function("GetTrim", &wrap_FGFDMExec_GetTrim_29)
    .function("GetEnginePath", &wrap_FGFDMExec_GetEnginePath_30)
    .function("GetAircraftPath", &wrap_FGFDMExec_GetAircraftPath_31)
    .function("GetSystemsPath", &wrap_FGFDMExec_GetSystemsPath_32)
    .function("GetFullAircraftPath", &wrap_FGFDMExec_GetFullAircraftPath_33)
    .function("GetOutputPath", &wrap_FGFDMExec_GetOutputPath_34)
    .function("GetPropertyValue", &wrap_FGFDMExec_GetPropertyValue_35)
    .function("SetPropertyValue", &wrap_FGFDMExec_SetPropertyValue_36)
    .function("GetModelName", &wrap_FGFDMExec_GetModelName_37)
    .function("GetPropertyManager", &wrap_FGFDMExec_GetPropertyManager_38)
    .function("EnumerateFDMs", &wrap_FGFDMExec_EnumerateFDMs_39)
    .function("GetFDMCount", &wrap_FGFDMExec_GetFDMCount_40)
    .function("GetChildFDM", &wrap_FGFDMExec_GetChildFDM_41)
    .function("SetChild", &wrap_FGFDMExec_SetChild_42)
    .function("SetOutputDirectives", &wrap_FGFDMExec_SetOutputDirectives_43)
    .function("ForceOutput", &wrap_FGFDMExec_ForceOutput_44)
    .function("SetLoggingRate", &wrap_FGFDMExec_SetLoggingRate_45)
    .function("SetOutputFileName", &wrap_FGFDMExec_SetOutputFileName_46)
    .function("GetOutputFileName", &wrap_FGFDMExec_GetOutputFileName_47)
    .function("DoTrim", &wrap_FGFDMExec_DoTrim_48)
    .function("DoLinearization", &wrap_FGFDMExec_DoLinearization_49)
    .function("DisableOutput", &wrap_FGFDMExec_DisableOutput_50)
    .function("EnableOutput", &wrap_FGFDMExec_EnableOutput_51)
    .function("Hold", &wrap_FGFDMExec_Hold_52)
    .function("EnableIncrementThenHold", &wrap_FGFDMExec_EnableIncrementThenHold_53)
    .function("CheckIncrementalHold", &wrap_FGFDMExec_CheckIncrementalHold_54)
    .function("Resume", &wrap_FGFDMExec_Resume_55)
    .function("Holding", &wrap_FGFDMExec_Holding_56)
    .function("ResetToInitialConditions", &wrap_FGFDMExec_ResetToInitialConditions_57)
    .function("SetDebugLevel", &wrap_FGFDMExec_SetDebugLevel_58)
    .function("BuildPropertyCatalog", &wrap_FGFDMExec_BuildPropertyCatalog_59)
    .function("QueryPropertyCatalog", &wrap_FGFDMExec_QueryPropertyCatalog_60)
    .function("PrintPropertyCatalog", &wrap_FGFDMExec_PrintPropertyCatalog_61)
    .function("PrintSimulationConfiguration", &wrap_FGFDMExec_PrintSimulationConfiguration_62)
    .function("GetPropertyCatalog", &wrap_FGFDMExec_GetPropertyCatalog_63)
    .function("SetTrimStatus", &wrap_FGFDMExec_SetTrimStatus_64)
    .function("GetTrimStatus", &wrap_FGFDMExec_GetTrimStatus_65)
    .function("SetTrimMode", &wrap_FGFDMExec_SetTrimMode_66)
    .function("GetTrimMode", &wrap_FGFDMExec_GetTrimMode_67)
    .function("GetPropulsionTankReport", &wrap_FGFDMExec_GetPropulsionTankReport_68)
    .function("GetSimTime", &wrap_FGFDMExec_GetSimTime_69)
    .function("GetDeltaT", &wrap_FGFDMExec_GetDeltaT_70)
    .function("SuspendIntegration", &wrap_FGFDMExec_SuspendIntegration_71)
    .function("ResumeIntegration", &wrap_FGFDMExec_ResumeIntegration_72)
    .function("IntegrationSuspended", &wrap_FGFDMExec_IntegrationSuspended_73)
    .function("Setsim_time", &wrap_FGFDMExec_Setsim_time_74)
    .function("Setdt", &wrap_FGFDMExec_Setdt_75)
    .function("SetRootDir", &wrap_FGFDMExec_SetRootDir_76)
    .function("GetRootDir", &wrap_FGFDMExec_GetRootDir_77)
    .function("IncrTime", &wrap_FGFDMExec_IncrTime_78)
    .function("GetFrame", &wrap_FGFDMExec_GetFrame_79)
    .function("GetDebugLevel", &wrap_FGFDMExec_GetDebugLevel_80)
    .function("Initialize", &wrap_FGFDMExec_Initialize_81)
    .function("SetHoldDown", &wrap_FGFDMExec_SetHoldDown_82)
    .function("GetHoldDown", &wrap_FGFDMExec_GetHoldDown_83)
    .function("GetTemplateFunc", &wrap_FGFDMExec_GetTemplateFunc_84)
    .function("AddTemplateFunc", &wrap_FGFDMExec_AddTemplateFunc_85)
    .function("GetRandomGenerator", &wrap_FGFDMExec_GetRandomGenerator_86)
    .function("SRand", &wrap_FGFDMExec_SRand_87);
}
