import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {FlightEngine} from './engine';
import {ArcadeFlight} from './flight-physics';
import './style.css';

const places={sf:{name:'San Francisco Bay',lat:37.795,lon:-122.46},ny:{name:'New York Harbor',lat:40.685,lon:-74.025},rio:{name:'Rio de Janeiro',lat:-22.975,lon:-43.18},montreal:{name:'Montreal',lat:45.5017,lon:-73.5673},amalfi:{name:'Amalfi Coast',lat:40.634,lon:14.6027},formia:{name:'Formia, Italy',lat:41.2564,lon:13.6069},tokyo:{name:'Tokyo',lat:35.6812,lon:139.7671},la:{name:'Los Angeles',lat:34.0522,lon:-118.2437},toronto:{name:'Toronto',lat:43.6426,lon:-79.3871},vancouver:{name:'Vancouver',lat:49.2827,lon:-123.1207},austin:{name:'Austin',lat:30.2672,lon:-97.7431},miami:{name:'Miami',lat:25.7617,lon:-80.1918},colorado:{name:'Colorado — Denver',lat:39.7392,lon:-104.9903,altitude:2800},canyon:{name:'Grand Canyon',lat:36.1069,lon:-112.1129,altitude:3000}};
const cameraNames=['Chase','Pilot','Orbit'];
function Icon({name}){const paths={plane:<><path d="m12 3 2 7 7 5v2l-7-2v4l2 2h-8l2-2v-4l-7 2v-2l7-5Z"/></>,camera:<><path d="M3 7h5l2-3h4l2 3h5v13H3Z"/><circle cx="12" cy="13" r="4"/></>,reset:<><path d="M4 10a8 8 0 1 1 1 8M4 4v6h6"/></>,mountain:<><path d="m2 20 7-14 5 8 3-5 5 11ZM6 12l3 2 2-3"/></>,controls:<><path d="M4 6h16M4 12h16M4 18h16"/><circle cx="8" cy="6" r="2"/><circle cx="16" cy="12" r="2"/><circle cx="10" cy="18" r="2"/></>};return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>}
function Modal({title,close,children,dismissible=true}){const ref=useRef();useEffect(()=>{const dialog=ref.current;dialog.showModal();return()=>dialog.close();},[]);return <dialog ref={ref} onKeyDown={e=>{if(e.key==='Escape'&&!dismissible)e.preventDefault();}} onCancel={e=>{e.preventDefault();if(dismissible)close();}} onClick={e=>{if(dismissible&&e.target===ref.current)close();}}><div className="modal-head"><h2>{title}</h2>{dismissible&&<button onClick={close} aria-label="Close dialog">×</button>}</div>{children}</dialog>}
function AircraftSetting({aircraft='cessna',loading,onChange,disabled=false}){return <><label>Aircraft<select value={aircraft} disabled={disabled||loading} onChange={e=>onChange(e.target.value)}><option value="cessna">Cessna 172</option><option value="rafale">Rafale M — F-16 physics</option></select></label><p className="note">{loading?'Loading aircraft and flight physics...':aircraft==='rafale'?'Rafale M appearance with JSBSim F-16 flight dynamics, not a Rafale performance simulation. W/S controls thrust; the upper half of the throttle engages afterburner.':'Original Cessna with your choice of Arcade or Realistic physics.'} Changing aircraft restarts and pauses your flight.</p></>}
function PhysicsSetting({model='arcade',loading=false,onChange,disabled=false,aircraft='cessna'}){return <><label>Flight physics<select value={model} onChange={e=>onChange(e.target.value)} disabled={disabled||loading||aircraft==='rafale'} aria-describedby="physics-help"><option value="arcade">Arcade (default)</option><option value="realistic">Realistic (JSBSim)</option></select></label><p id="physics-help" className="note">{loading?'Loading flight physics...':model==='realistic'?(aircraft==='rafale'?'F-16 aerodynamics and jet engine simulation powered by JSBSim.':'Cessna 172P aerodynamics and engine simulation powered by JSBSim.'):'Our previous flight physics, with the original handling and acrobatics.'} Changing physics restarts and pauses your flight at the selected departure.</p></>}
function Controls({close,start,acrobatic,toggleAcrobatic,physicsModel,physicsLoading,setPhysicsModel,aircraft,aircraftLoading,setAircraft}){return <Modal title="Flight settings" close={close}><AircraftSetting aircraft={aircraft} loading={aircraftLoading} disabled={physicsLoading||aircraftLoading} onChange={setAircraft}/><PhysicsSetting aircraft={aircraft} model={physicsModel} loading={physicsLoading} onChange={setPhysicsModel} disabled={aircraftLoading}/><button className="full" aria-pressed={acrobatic} disabled={physicsLoading||aircraftLoading} onClick={toggleAcrobatic}>Acrobatic mode: {acrobatic?'On':'Off'}</button><p className="note">{physicsModel==='realistic'?'Normal mode assists pitch and bank; Acrobatic mode gives direct control of the surfaces. Both use the selected aircraft model.':'Normal mode assists pitch and bank; Acrobatic mode restores the previous unrestricted maneuvers.'} Acrobatic mode keeps the camera behind the plane.</p><div className="key-list">{[['↑','Nose down'],['↓','Nose up'],['← / →','Bank left / right'],['A / D','Rudder left / right'],['W / S','Increase / decrease throttle'],['Space','Start / pause / resume'],['C','Change camera'],['R','Reset flight'],['F','Toggle Acrobatic mode']].map(([key,label])=><div key={key}><kbd>{key}</kbd><span>{label}</span></div>)}</div><p className="note">Starts airborne; terrain and building collisions are not simulated. Switching away pauses your flight.</p><button className="primary full" disabled={physicsLoading||aircraftLoading} onClick={start}>Ready to fly</button></Modal>}
function Scenery({engine,close,onLocation,physicsModel,physicsLoading,setPhysicsModel,aircraft,aircraftLoading,setAircraft}){const [key,setKey]=useState(''),[place,setPlace]=useState('sf'),[busy,setBusy]=useState(false),[error,setError]=useState('');return <Modal title="Choose your scenery" dismissible={!!engine?.google&&!busy} close={()=>{if(!busy)close();}}><h3>Google Photorealistic 3D Tiles</h3><p>Fly above real cities and landscapes. Requires your own Google Maps API key with Map Tiles API and billing enabled.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await engine.connectGoogle(key.trim(),places[place]);onLocation(places[place].name);setKey('');close();}catch{setError('Unable to start scenery. Check the flight-engine download, Google key, Map Tiles API, billing, and referrer restrictions, then try again.');}finally{setBusy(false);}}}><label>Departure area<select value={place} onChange={e=>setPlace(e.target.value)} disabled={busy}>{Object.entries(places).map(([id,p])=><option value={id} key={id}>{p.name}</option>)}</select></label><AircraftSetting aircraft={aircraft} loading={aircraftLoading} onChange={setAircraft} disabled={busy||physicsLoading}/><PhysicsSetting aircraft={aircraft} model={physicsModel} loading={physicsLoading} onChange={setPhysicsModel} disabled={busy||aircraftLoading}/><label>Google Maps API key<input type="password" autoComplete="off" placeholder="Enter your browser-restricted API key" value={key} onChange={e=>setKey(e.target.value)} required disabled={busy}/></label><p className="note">Kept only in memory and sent to Google for tile requests. Restrict your key to this app’s URL. Google imagery is streamed; real-world collisions are not simulated.</p>{error&&<p className="error" role="alert">{error}</p>}<button className="primary full" disabled={busy||physicsLoading||aircraftLoading||!key.trim()||!engine}>{busy?'Preparing your flight…':'Connect & explore'}</button><a className="docs" href="https://developers.google.com/maps/documentation/tile/get-api-key" target="_blank" rel="noreferrer">Google API setup guide ↗</a></form></Modal>}
function App(){const mount=useRef(),engine=useRef();const [flight,setFlight]=useState(()=>({...new ArcadeFlight().state,aircraft:'cessna',aircraftLoading:false,physicsModel:'arcade',physicsStatus:'ready',running:false,cameraMode:0,mode:'setup'})),[modal,setModal]=useState('scenery'),[location,setLocation]=useState('Choose a destination'),[error,setError]=useState(''),[ready,setReady]=useState(false);
 useEffect(()=>{try{engine.current=new FlightEngine(mount.current,setFlight,setError);setReady(true);}catch{setError('The 3D renderer could not start. Enable WebGL / hardware acceleration and reload.');}return()=>engine.current?.destroy();},[]);
 const heading=((flight.heading*180/Math.PI)%360+360)%360;const altitude=Math.round(flight.y*3.28084);
 const showModal=name=>{engine.current.running=false;engine.current.keys.clear();engine.current.emit();setModal(name);};
 return <main><div className="viewport" ref={mount} aria-label="3D flight simulation"/><div className="hud">
  <header><div className="instruments panel"><div><label>AIRSPEED</label><strong data-testid="airspeed">{Math.round(flight.speed*1.94384)}</strong><small>kt</small></div><div><label>ALTITUDE</label><strong data-testid="altitude">{altitude.toLocaleString('en-US')}</strong><small>ft MSL</small></div><div className="throttle"><label htmlFor="throttle">THROTTLE</label><strong>{Math.round(flight.throttle*100)}<em>%</em></strong><input id="throttle" aria-label="Throttle" type="range" min="0" max="100" value={Math.round(flight.throttle*100)} onChange={e=>{engine.current.state.throttle=Number(e.target.value)/100;engine.current.emit();}} disabled={!ready}/></div></div><div className="compass"><div className="compass-scale"><span>{Math.round((heading+300)%360)}°</span><span>{Math.round((heading+330)%360)}°</span><b>{Math.round(heading).toString().padStart(3,'0')}°</b><span>{Math.round((heading+30)%360)}°</span><span>{Math.round((heading+60)%360)}°</span></div><i/><small>HEADING</small></div><nav><button disabled={!ready} aria-label="Scenery" onClick={()=>showModal('scenery')}><Icon name="mountain"/><span>Scenery</span></button><button disabled={!ready} aria-label="Settings" onClick={()=>showModal('controls')}><Icon name="controls"/><span>Settings</span></button></nav></header>
  {flight.mode==='google'&&(!flight.running||flight.stall)&&<div className={'flight-status '+(flight.crashed||flight.stall?'alert':'')} role="status">{flight.crashed?'Flight ended · reset to try again':flight.stall?'STALL · lower the nose and add throttle':flight.time>0?'Flight paused':'The sky is yours.'}<small>{flight.crashed?'Reset to start another flight.':flight.stall?`${Math.round(flight.speed*1.94384)} kt · ease off the pitch and build airspeed`:flight.time>0?'Press Space to continue':'Press Space to start, then use the arrow keys to fly.'}</small></div>}
  {error&&<div className="error-banner" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss error">×</button></div>}
  <div className="touch-controls"><button aria-label="Bank left" onPointerDown={()=>engine.current.keys.add('ArrowLeft')} onPointerUp={()=>engine.current.keys.delete('ArrowLeft')} onPointerLeave={()=>engine.current.keys.delete('ArrowLeft')}>←</button><button aria-label="Nose up" onPointerDown={()=>engine.current.keys.add('ArrowDown')} onPointerUp={()=>engine.current.keys.delete('ArrowDown')} onPointerLeave={()=>engine.current.keys.delete('ArrowDown')}>↑</button><button aria-label="Nose down" onPointerDown={()=>engine.current.keys.add('ArrowUp')} onPointerUp={()=>engine.current.keys.delete('ArrowUp')} onPointerLeave={()=>engine.current.keys.delete('ArrowUp')}>↓</button><button aria-label="Bank right" onPointerDown={()=>engine.current.keys.add('ArrowRight')} onPointerUp={()=>engine.current.keys.delete('ArrowRight')} onPointerLeave={()=>engine.current.keys.delete('ArrowRight')}>→</button></div>
  <footer><span>{location} <b>/</b> {flight.mode==='google'?`Google 3D scenery · ${flight.aircraft==='rafale'?'F-16 physics':flight.physicsModel==='realistic'?'Realistic':'Arcade'}`:'Select scenery to begin'}{['cessna','rafale'].includes(flight.aircraftStatus)&&<> <b>/</b> <a href="/aircraft-credits.html" target="_blank" rel="noreferrer">Aircraft: {flight.aircraft==='rafale'?'bohmerang':'osmosikum'}</a></>}{flight.aircraftStatus==='loading'&&<> <b>/</b> Loading Cessna…</>}</span><span>{Math.floor(flight.time/60).toString().padStart(2,'0')}:{Math.floor(flight.time%60).toString().padStart(2,'0')} <b>/</b> {cameraNames[flight.cameraMode]} camera{flight.acrobatic&&<> <b>/</b> Acrobatic mode</>}</span></footer>
 </div>{modal==='controls'&&<Controls aircraft={flight.aircraft} aircraftLoading={flight.aircraftLoading} setAircraft={aircraft=>engine.current.setAircraft(aircraft)} physicsModel={flight.physicsModel} physicsLoading={flight.physicsStatus==='loading'} setPhysicsModel={model=>engine.current.setPhysicsModel(model)} acrobatic={!!flight.acrobatic} toggleAcrobatic={()=>engine.current.toggleAcrobatic()} close={()=>{setModal(null);document.activeElement?.blur();}} start={()=>{setModal(null);document.activeElement?.blur();if(!engine.current.running)engine.current.toggle();}}/>} {modal==='scenery'&&<Scenery aircraft={flight.aircraft} aircraftLoading={flight.aircraftLoading} setAircraft={aircraft=>engine.current.setAircraft(aircraft)} physicsModel={flight.physicsModel} physicsLoading={flight.physicsStatus==='loading'} setPhysicsModel={model=>engine.current.setPhysicsModel(model)} engine={engine.current} close={()=>setModal(null)} onLocation={setLocation}/>}</main>;
}
createRoot(document.getElementById('root')).render(<App/>);

