import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {FlightEngine} from './engine';
import {initialState,checkpoints} from './physics';
import './style.css';

const places={sf:{name:'San Francisco Bay',lat:37.795,lon:-122.46},ny:{name:'New York Harbor',lat:40.685,lon:-74.025},rio:{name:'Rio de Janeiro',lat:-22.975,lon:-43.18},montreal:{name:'Montreal',lat:45.5017,lon:-73.5673},amalfi:{name:'Amalfi Coast',lat:40.634,lon:14.6027}};
const cameraNames=['Chase','Pilot','Orbit'];
function Icon({name}){const paths={plane:<><path d="m12 3 2 7 7 5v2l-7-2v4l2 2h-8l2-2v-4l-7 2v-2l7-5Z"/></>,camera:<><path d="M3 7h5l2-3h4l2 3h5v13H3Z"/><circle cx="12" cy="13" r="4"/></>,reset:<><path d="M4 10a8 8 0 1 1 1 8M4 4v6h6"/></>,mountain:<><path d="m2 20 7-14 5 8 3-5 5 11ZM6 12l3 2 2-3"/></>,controls:<><path d="M4 6h16M4 12h16M4 18h16"/><circle cx="8" cy="6" r="2"/><circle cx="16" cy="12" r="2"/><circle cx="10" cy="18" r="2"/></>};return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>}
function Modal({title,close,children}){const ref=useRef();useEffect(()=>{const dialog=ref.current;dialog.showModal();return()=>dialog.close();},[]);return <dialog ref={ref} onCancel={e=>{e.preventDefault();close();}} onClick={e=>{if(e.target===ref.current)close();}}><div className="modal-head"><h2>{title}</h2><button onClick={close} aria-label="Close dialog">×</button></div>{children}</dialog>}
function Controls({close,start}){return <Modal title="Your flight controls" close={close}><p>Start airborne. Fly through the orange rings, or simply explore.</p><div className="key-list">{[['↑','Nose down'],['↓','Nose up'],['← / →','Bank left / right'],['A / D','Rudder left / right'],['W / S','Increase / decrease throttle'],['Space','Start / pause / resume'],['C','Change camera'],['R','Reset flight']].map(([key,label])=><div key={key}><kbd>{key}</kbd><span>{label}</span></div>)}</div><p className="note">An arcade flight model for exploration. Starts in the air; no takeoff or landing simulation. Switching away pauses your flight.</p><button className="primary full" onClick={start}>Ready to fly</button></Modal>}
function Scenery({engine,close,onLocation}){const [key,setKey]=useState(''),[place,setPlace]=useState('sf'),[busy,setBusy]=useState(false),[error,setError]=useState('');return <Modal title="Choose your scenery" close={()=>{if(!busy)close();}}><button className="scene-option" disabled={busy} onClick={()=>{engine.practice();onLocation('Practice islands');close();}}><Icon name="mountain"/><span><strong>Practice islands</strong><small>Generated landscape · ready to fly</small></span><span>↗</span></button><h3>Google Photorealistic 3D Tiles</h3><p>Fly above real cities. Requires your own Google Maps API key with Map Tiles API and billing enabled.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await engine.connectGoogle(key.trim(),places[place]);onLocation(places[place].name);setKey('');close();}catch{setError('Unable to connect. Verify the key, Map Tiles API, billing, and HTTP referrer restrictions. Practice mode remains available.');}finally{setBusy(false);}}}><label>Departure area<select value={place} onChange={e=>setPlace(e.target.value)} disabled={busy}>{Object.entries(places).map(([id,p])=><option value={id} key={id}>{p.name}</option>)}</select></label><label>Google Maps API key<input type="password" autoComplete="off" placeholder="Enter your browser-restricted API key" value={key} onChange={e=>setKey(e.target.value)} required disabled={busy}/></label><p className="note">Kept only in memory and sent to Google for tile requests. Restrict your key to this app’s URL. Google imagery is streamed; real-world collisions are not simulated.</p>{error&&<p className="error" role="alert">{error}</p>}<button className="primary full" disabled={busy||!key.trim()}>{busy?'Connecting to Google…':'Connect & explore'}</button><a className="docs" href="https://developers.google.com/maps/documentation/tile/get-api-key" target="_blank" rel="noreferrer">Google API setup guide ↗</a></form></Modal>}
function App(){const mount=useRef(),engine=useRef();const [flight,setFlight]=useState({...initialState(),running:false,cameraMode:0,mode:'practice'}),[modal,setModal]=useState(null),[location,setLocation]=useState('Practice islands'),[error,setError]=useState(''),[ready,setReady]=useState(false);
 useEffect(()=>{try{engine.current=new FlightEngine(mount.current,setFlight,setError);setReady(true);}catch{setError('The 3D renderer could not start. Enable WebGL / hardware acceleration and reload.');}return()=>engine.current?.destroy();},[]);
 const heading=((flight.heading*180/Math.PI)%360+360)%360;const altitude=Math.round(flight.y*3.28084);const active=checkpoints[flight.checkpoint];const distance=active?Math.hypot(active.x-flight.x,active.z-flight.z)/1852:0;
 const showModal=name=>{engine.current.running=false;engine.current.keys.clear();engine.current.emit();setModal(name);};
 return <main><div className="viewport" ref={mount} aria-label="3D flight simulation"/><div className="hud">
  <header><div className="instruments panel"><div><label>AIRSPEED</label><strong data-testid="airspeed">{Math.round(flight.speed*1.94384)}</strong><small>kt</small></div><div><label>ALTITUDE</label><strong data-testid="altitude">{altitude.toLocaleString('en-US')}</strong><small>ft MSL</small></div><div className="throttle"><label htmlFor="throttle">THROTTLE</label><strong>{Math.round(flight.throttle*100)}<em>%</em></strong><input id="throttle" aria-label="Throttle" type="range" min="0" max="100" value={Math.round(flight.throttle*100)} onChange={e=>{engine.current.state.throttle=Number(e.target.value)/100;engine.current.emit();}} disabled={!ready}/></div></div><div className="compass"><div className="compass-scale"><span>{Math.round((heading+300)%360)}°</span><span>{Math.round((heading+330)%360)}°</span><b>{Math.round(heading).toString().padStart(3,'0')}°</b><span>{Math.round((heading+30)%360)}°</span><span>{Math.round((heading+60)%360)}°</span></div><i/><small>HEADING</small></div><nav><button disabled={!ready} aria-label="Scenery" onClick={()=>showModal('scenery')}><Icon name="mountain"/><span>Scenery</span></button><button disabled={!ready} aria-label="Controls" onClick={()=>showModal('controls')}><Icon name="controls"/><span>Controls</span></button></nav></header>
  {(!flight.running||flight.stall)&&<div className={'flight-status '+(flight.crashed||flight.stall?'alert':'')} role="status">{flight.crashed?'Flight ended · reset to try again':flight.stall?'STALL · lower the nose and add throttle':flight.time>0?'Flight paused':'The sky is yours.'}<small>{flight.crashed?'You reached the practice terrain.':flight.stall?`${Math.round(flight.speed*1.94384)} kt · airspeed too low`:flight.time>0?'Press Space to continue':'Press Space to start, then use the arrow keys to fly.'}</small></div>}
  {error&&<div className="error-banner" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss error">×</button></div>}
  <section className="bottom-hud">

  {flight.mode==='practice'&&<div className="flight-plan panel"><h2>FLIGHT PLAN<span>{`${flight.checkpoint} / 3`}</span></h2>{checkpoints.map((p,i)=><div className={'waypoint '+(i===flight.checkpoint?'active':'')} key={p.name}><span>{i<flight.checkpoint?'✓':String(i+1).padStart(2,'0')}</span><span>{p.name}</span><small>{i<flight.checkpoint?'PASSED':i===flight.checkpoint?`${distance.toFixed(1)} NM`:'○'}</small></div>)}{flight.mode==='practice'&&flight.checkpoint===3&&<p className="complete">Route complete. Beautiful flying!</p>}</div>}</section>
  <div className="touch-controls"><button aria-label="Bank left" onPointerDown={()=>engine.current.keys.add('ArrowLeft')} onPointerUp={()=>engine.current.keys.delete('ArrowLeft')} onPointerLeave={()=>engine.current.keys.delete('ArrowLeft')}>←</button><button aria-label="Nose up" onPointerDown={()=>engine.current.keys.add('ArrowDown')} onPointerUp={()=>engine.current.keys.delete('ArrowDown')} onPointerLeave={()=>engine.current.keys.delete('ArrowDown')}>↑</button><button aria-label="Nose down" onPointerDown={()=>engine.current.keys.add('ArrowUp')} onPointerUp={()=>engine.current.keys.delete('ArrowUp')} onPointerLeave={()=>engine.current.keys.delete('ArrowUp')}>↓</button><button aria-label="Bank right" onPointerDown={()=>engine.current.keys.add('ArrowRight')} onPointerUp={()=>engine.current.keys.delete('ArrowRight')} onPointerLeave={()=>engine.current.keys.delete('ArrowRight')}>→</button></div>
  <footer><span>{location} <b>/</b> {flight.mode==='practice'?'Generated terrain':'Google 3D scenery'}{flight.aircraftStatus==='cessna'&&<> <b>/</b> <a href="/aircraft-credits.html" target="_blank" rel="noreferrer">Aircraft: osmosikum</a></>}{flight.aircraftStatus==='loading'&&<> <b>/</b> Loading Cessna…</>}</span><span>{Math.floor(flight.time/60).toString().padStart(2,'0')}:{Math.floor(flight.time%60).toString().padStart(2,'0')} <b>/</b> {cameraNames[flight.cameraMode]} camera</span></footer>
 </div>{modal==='controls'&&<Controls close={()=>{setModal(null);document.activeElement?.blur();}} start={()=>{setModal(null);document.activeElement?.blur();if(!engine.current.running)engine.current.toggle();}}/>} {modal==='scenery'&&<Scenery engine={engine.current} close={()=>setModal(null)} onLocation={setLocation}/>}</main>;
}
createRoot(document.getElementById('root')).render(<App/>);

